var API_CONTEXT = "API";
var SOCKET_CONTEXT = "SOCKET.IO";

var CHANGE_IN_SLA = "change_in_slas";
var CHANGE_IN_INTEGRATION_FLOW = "change_in_int_flow";
var CHANGE_IN_DAILY_SUMM = "change_in_daily_summ";
var CHANGE_IN_LATEST_SUMM = "change_in_latest_summ";


var CONSTANTS = {
		API_CONTEXT:API_CONTEXT,
		SOCKET_CONTEXT:SOCKET_CONTEXT,
		CHANGE_IN_SLA:CHANGE_IN_SLA,
		CHANGE_IN_INTEGRATION_FLOW:CHANGE_IN_INTEGRATION_FLOW,
		CHANGE_IN_DAILY_SUMM:CHANGE_IN_DAILY_SUMM,
		CHANGE_IN_LATEST_SUMM:CHANGE_IN_LATEST_SUMM
}

module.exports = CONSTANTS;